users:

default_role: default

roles:
  default:
    prefix:
    suffix:
    chatcolor:
    namecolor:
    perms:

  owner:
    prefix:  #Leave blank if needed
    suffix:  #Leave blank if needed
    namecolor: &4 #Assign the color using &
    chatcolor:
    perms:
      - *